name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install
      
      - name: Generate Pages
        run: pnpm generate
      
      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Set up SSH key
        env:
          STATIC_DIR: ${{ secrets.STATIC_DIR }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SSH_SERVER }}
          USER: ${{ secrets.SSH_USERNAME }}
          PROT: ${{ secrets.PROT }}
          MKDIRTEST: ${{ secrets.PATH }}
        run: |
          mkdir -p ~/.ssh && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          scp -P ${PROT} -o StrictHostKeyChecking=no -r ./.output/public/* ${USER}@${HOST}:${MKDIRTEST}

      

