name: Push and SSH
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  # 替换为你希望使用的 Node.js 版本

      - name: Install Dependencies
        run: npm install

      - name: Generate Pages
        run: npm run generate

      - name: Set up SSH key
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SSH_SERVER }}
          USER: ${{ secrets.SSH_USERNAME }}
          PROT: ${{ secrets.PROT }}
          MKDIRTEST: ${{ secrets.PATH }}
        run: |
          mkdir -p ~/.ssh && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          scp -P ${PROT} -o StrictHostKeyChecking=no -r .output/public/* ${USER}@${HOST}:${MKDIRTEST}

    #   - name: Run SSH command
    #     run: ssh user@server 'your-command'